import Head from "next/head";
import { Inter } from "@next/font/google";

import styles from "../styles/main.module.scss";
import Main1 from "../src/common/main1";
import Main2 from "../src/common/main2";
import Main3 from "../src/common/main3";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <link
          rel="shortcut icon"
          href="/InstagramIcon.png.webp"
          type="image/x-icon"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.all}>
        <Main1 />
        <Main2 />
        <Main3 />
      </div>
    </>
  );
}
